# Generated by Django 5.1.4 on 2025-01-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_private',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=7),
        ),
    ]
